code/quiosko/urls.py
from django.contrib.auth.views import LoginView
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from .views import LoginPage, LogoutPage

urlpatterns = [
    url(r'^$', LoginPage.as_view(), name='accesar'),
    url(r'^admin/', admin.site.urls),
    url(r'^login$', LoginPage.as_view(), name='accesar'),
    url(r'^logout$', LogoutPage.as_view(), name='accesar'),
    url(r'facturacion', include('facturacion.urls')),
    url(r'^reporte', include('reporte.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/reporte/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'diario$', views.ReporteDiarioPage.as_view(), name='reporte_diario'),
    url(r'pdf$', views.ReporteDiario2PDF.as_view(), name='reportediario2pdf'),
]

code/facturacion/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator
from django.utils.encoding import python_2_unicode_compatible # only if you need to support Python 2
# Create your models here.

@python_2_unicode_compatible  # only if you need to support Python 2
class Cliente(models.Model):
	ruc 		= models.CharField(max_length=15, null=False, blank=False, unique=True)
	email 		= models.EmailField(max_length=200, null=False, blank=False)
	firstname 	= models.CharField(max_length= 100, null=False, blank=False)
	lastname 	= models.CharField(max_length= 100, null=True, blank=True)
	phone		= models.CharField(max_length= 20, null=True, blank=True)
	created		= models.DateTimeField(auto_now=False, auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True, auto_now_add=False)
	
	def __unicode__(self):
		return str(self.ruc)

	def __str__(self):
		return str(self.ruc)


@python_2_unicode_compatible  # only if you need to support Python 2
class TablaCatalogo(models.Model):
	code 		= models.CharField(max_length= 6, null=False, blank=False, unique=True)
	description	= models.CharField(max_length= 50, null=False, blank=False,)
	value		= models.IntegerField(null=True, blank=True)
	created		= models.DateTimeField(auto_now=False, auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True, auto_now_add=False)
	
	def __unicode__(self):
		return str(self.value)

	def __str__(self):
		return str(self.value)


@python_2_unicode_compatible  # only if you need to support Python 2
class Producto(models.Model):
	name 		= models.CharField(max_length=200, null=False, blank=False)
	price 		= models.DecimalField(decimal_places=2, max_digits=20, validators=[MinValueValidator(0)])
	sale_price 	= models.DecimalField(decimal_places=2, max_digits=20, validators=[MinValueValidator(0)])
	tablacatalogo = models.ForeignKey(TablaCatalogo)
	stock		= models.PositiveSmallIntegerField(null=True, blank=True)
	created		= models.DateTimeField(auto_now=False, auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True, auto_now_add=False)
	
	def __unicode__(self):
		return str(self.name)

	def __str__(self):
		return str(self.name)


@python_2_unicode_compatible  # only if you need to support Python 2
class DocumentoCabecera(models.Model):
	seller		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	cliente		= models.ForeignKey(Cliente)
	ruc 		= models.CharField(max_length=15, default='0999999999001', null=False, blank=False)
	docid 		= models.CharField(max_length= 17, null=False, blank=False, unique=True)
	doctype		= models.CharField(max_length=3,choices=(('-','-'),('Fac','Factura'),('Ret','Retencion'),('NC','Nota Credito'),),default='Fac',)
	payment		= models.CharField(max_length=3,choices=(('-','-'),('Efe','Efectivo'),('Che','Cheque'),('Deb','Debito'),('Tar','Tarjeta'),),default='Efe',)
	iva			= models.DecimalField(decimal_places=2, max_digits=20, validators=[MinValueValidator(0)])
	created		= models.DateTimeField(auto_now=False, auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True, auto_now_add=False)
	
	def __unicode__(self):
		return str(self.docid)

	def __str__(self):
		return str(self.docid)


@python_2_unicode_compatible  # only if you need to support Python 2
class DocumentoDetalle(models.Model):
	documento	= models.ForeignKey(DocumentoCabecera)
	producto	= models.ForeignKey(Producto)
	tablacatalogo = models.ForeignKey(TablaCatalogo)
	cantidad	= models.PositiveSmallIntegerField(null=False, blank=False)
	descuento	= models.DecimalField(decimal_places=2, max_digits=20, validators=[MinValueValidator(0)], default='0.00')
	subtotal	= models.DecimalField(decimal_places=2, max_digits=20, validators=[MinValueValidator(0)], default='0.00')
	created		= models.DateTimeField(auto_now=False, auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True, auto_now_add=False)
	
	def __unicode__(self):
		return str(self.id)

	def __str__(self):
		return str(self.id)

code/reporte/models.py
from django.db import models

# Create your models here.

code/reporte/forms.py
from django import forms
from django.utils.timezone import datetime

from facturacion.models import  DocumentoCabecera

class FormReporteDiario(forms.Form):
	fecha = forms.DateField(initial=datetime.today())
	

code/reporte/views.py
import os
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import FloatField, Sum, F
from django.http import HttpResponse
from django.template.loader import get_template
from django.shortcuts import render
from django.utils.timezone import datetime
from django.views import View

from decimal import *
from facturacion.models import DocumentoCabecera, DocumentoDetalle
from .forms import FormReporteDiario

from xhtml2pdf import pisa

# Create your views here.
class ReporteDiarioPage(LoginRequiredMixin, View):
	login_url 	= '/login'
	fecha 		= datetime.today()
	totaldia = Decimal('0.00')
	def get(self, request, *args, **kwargs):
		usuario = request.user
		if usuario.groups.filter(name='Supervisor').exists():
			form	= FormReporteDiario()
			qs = DocumentoCabecera.objects.filter(created__date=self.fecha).annotate(
				total1=Sum(F('documentodetalle__subtotal'))
				).annotate(
				total2=F('iva')+Sum(F('documentodetalle__subtotal'))
				)
			for ventasdia in qs:
				self.totaldia = self.totaldia + ventasdia.total2
			context = {
				'title': '',
				'description': '',
				'form': form,
				'facturas': qs,
				'totaldia': self.totaldia
			}
			return render(request,"reporte_diario.html",context)
		else:
			return HttpResponse("Su usuario no tiene permisos pera ver el reporte.")

	def post(self, request, *args, **kwargs):
		usuario = request.user
		if usuario.groups.filter(name='Supervisor').exists():
			form	= FormReporteDiario(request.POST)
			if form.is_valid():
				self.fecha = form.cleaned_data.get('fecha')
			qs = DocumentoCabecera.objects.filter(created__date=self.fecha).annotate(
				total1=Sum(F('documentodetalle__subtotal'))
				).annotate(
				total2=F('iva')+Sum(F('documentodetalle__subtotal'))
				)
			for ventasdia in qs:
				self.totaldia = self.totaldia + ventasdia.total2
			context = {
				'title': '',
				'description': '',
				'form': form,
				'facturas': qs,
				'totaldia': self.totaldia
			}
			return render(request,"reporte_diario.html",context)
		else:
			return HttpResponse("Su usuario no tiene permisos pera ver el reporte.")
		

class ReporteDiario2PDF(LoginRequiredMixin, View):
	login_url 	= '/login'
	fecha 		= datetime.today()
	totaldia = Decimal('0.00')

	def get(self, request, *args, **kwargs):
	# Prepare context
		usuario = request.user
		if usuario.groups.filter(name='Supervisor').exists():
			if request.GET.get('fecha'):
				self.fecha = request.GET.get('fecha')
			qs = DocumentoCabecera.objects.filter(created__date=self.fecha).annotate(
				total1=Sum(F('documentodetalle__subtotal'))
				).annotate(
				total2=F('iva')+Sum(F('documentodetalle__subtotal'))
				)
			for ventasdia in qs:
				self.totaldia = self.totaldia + ventasdia.total2
			context = {
				'title': '',
				'description': '',
				'fecha': self.fecha,
				'user': request.user,
				'totaldia': self.totaldia,
				'facturas': qs
			}
			# Render html content through html template with context
			template = get_template('reportediario2pdf.html')
			html = template.render(context)

			# Write PDF to file
			if not os.path.exists(settings.MEDIA_ROOT):
				os.makedirs(settings.MEDIA_ROOT)
			with open(os.path.join(settings.MEDIA_ROOT, 'reporte.pdf'), "w+b") as f:
			# f = open(os.path.join(settings.MEDIA_ROOT, 'test.pdf'), "w+b")
				pisaStatus = pisa.CreatePDF(html, dest=f)

				# Return PDF document through a Django HTTP response
				f.seek(0) #Set pointer at the beginning to read "goto() canvas()"
				pdf = f.read()
				f.close()            # Don't forget to close the file handle
			response = HttpResponse(pdf, content_type='application/pdf')
			filename = "Reporte_%s.pdf" %(self.fecha)
			content = "inline; filename='%s'" %(filename)
			download = request.GET.get("download")
			if download:
				content = "attachment; filename='%s'" %(filename)
			response['Content-Disposition'] = content
			return response
		else:
			return HttpResponse("Su usuario no tiene permisos pera ver el reporte.")
			

code/reporte/templates/reporte_diario.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block pagecontent %}
	<!-- Main component for a primary marketing message or call to action -->
	<div class="page-header">
		<h1>Reporte de Facturación</h1>
	</div>
	<div class="col-md-6">
		<form class="" method="post">
		{% csrf_token %}
			{{ form|crispy }}
			<button class="btn btn-primary" type="submit">Filtrar</button>
			<a href="/reporte/pdf" onclick="this.href=this.href +'?download=true' + '&fecha=' + document.getElementById('id_fecha').value"><button class="btn btn-danger" type="button" >Generar PDF</button></a>
		</form>
	</div>

	<table class="table">
		<thead>
			<tr>
				<th># Factura</th>
				<th>Vendedor</th>
				<th>Cliente</th>
				<th>Tipo Pago</th>
				<th>Subtotal</th>
				<th>Iva</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			{% for factura in facturas %}
			<tr>
				<td>{{ factura.docid }}</td>
				<td>{{ factura.seller }}</td>
				<td>{{ factura.cliente }}</td>
				<td>{{ factura.get_payment_display }}</td>
				<td class="totales">{{ factura.total1 }}</td>
				<td class="totales">{{ factura.iva }}</td>
				<td class="totales">{{ factura.total2 }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<p class="text-right"> <strong>Total venta diaria: ${{ totaldia }} </strong></p>
{% endblock %}

code/reporte/templates/reportediario2pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Reporte</title>
	<style>
	@page {
        size: letter landscape;
        margin: 2cm;
    }
	html{font-family:sans-serif;font-size:10px;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}table{border-spacing:0;border-collapse:collapse}td,th{padding:0}thead{display:table-header-group}tr{page-break-inside:avoid}h2,h3{orphans:3;widows:3}h2,h3{page-break-after:avoid}.table{border-collapse:collapse !important;background-color:transparent}body{font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-size:14px;line-height:1.42857143;color:#333;background-color:#fff}h2,h3,h5{font-family:inherit;font-weight:500;line-height:1.1;color:inherit}h2,h3{margin-top:20px;margin-bottom:10px}h5{margin-top:10px;margin-bottom:10px}h2{font-size:30px}h3{font-size:24px}h5{font-size:14px}.text-right{text-align:right}.text-center{text-align:center}.page-header{padding-bottom:9px;margin:40px 0 20px;border-bottom:1px solid #eee}.container{padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto}table{background-color:transparent}th{text-align:left}.table{width:100%;max-width:100%;margin-bottom:20px}.table>tbody>tr>td,.table>thead>tr>th{padding:8px;line-height:1.42857143;vertical-align:top;border-top:1px solid #ddd}.table>thead>tr>th{vertical-align:bottom;border-bottom:2px solid #ddd}.table>thead:first-child>tr:first-child>th{border-top:0}.table-striped>tbody>tr:nth-of-type(odd){background-color:#f9f9f9}.container:after,.container:before{display:table;content:" "}.container:after{clear:both}.totales::before{content: "$";}
	</style>
</head>
<body>
<div class="container">
<div class="page-header">
	<h3 class="text-center">Quiosco "Don Cortez"</h3>
	<h4 class="text-center">Reporte Venta: {{ fecha }}</h4>
</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th># Factura</th>
			<th class="text-center">Vendedor</th>
			<th>Cliente</th>
			<th>Tipo Pago</th>
			<th>Subotal</th>
			<th>Iva</th>
			<th>Total</th>
		</tr>
	</thead>
	<tbody>
		{% for factura in facturas %}
		<tr>
			<td>{{ factura.docid }}</td>
			<td class="text-center">{{ factura.seller }}</td>
			<td>{{ factura.cliente }}</td>
			<td>{{ factura.get_payment_display }}</td>
			<td>${{ factura.total1 }}</td>
			<td>${{ factura.iva }}</td>
			<td>${{ factura.total2 }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<p class="text-right"> <strong>Total venta diaria: ${{ totaldia }} </strong></p>
<h5 class="text-right">Generado por: {{ user }}</h5>
<h5 class="text-right">Fecha: {% now "d/m/Y H:i" %}</h5>
</div>
</body>
</html>